// This file is generated by scripts/generateEliteMobCombinations.mjs --write.
// Run npm run hunting:elite-combinations after changing hunting monster definitions, behavior, or generation rules.

export const ELITE_MOB_COMBINATION_GENERATION = Object.freeze({
    generatorVersion: "1",
    ruleVersion: "elite-mob-combination-v1",
    generatedAt: "reproducible",
    seed: 20260714,
    candidateCountPerSize: 48,
    repetitionsPerCharacter: 2,
    playerRosterCount: 13,
    maxSeconds: 30,
    floor: 50,
    stageId: "cave",
    uniqueMonsterTypes: [
        "barrier",
        "boomerang",
        "chain",
        "charger",
        "electric",
        "healer",
        "jumper",
        "laser",
        "pursuer",
        "shard",
        "shockwave",
        "shooter",
        "siphon",
        "splitter"
    ],
    scoreFormula: "monsterWinRate + winningRemainingHpRatio * 0.01",
    winningRemainingHpWeight: 0.01
});

export const ELITE_MOB_COMBINATIONS = Object.freeze([
    Object.freeze({
        id: "elite-3-1-siphon-siphon-siphon",
        size: 3,
        monsterTypes: Object.freeze(["siphon", "siphon", "siphon"]),
        metrics: Object.freeze({
            matches: 26,
            wins: 26,
            timeoutMatches: 0,
            monsterWinRate: 1,
            winningRemainingHpRatio: 0.998149,
            score: 1.009981
        })
    }),
    Object.freeze({
        id: "elite-4-1-boomerang-jumper-siphon-siphon",
        size: 4,
        monsterTypes: Object.freeze(["boomerang", "jumper", "siphon", "siphon"]),
        metrics: Object.freeze({
            matches: 26,
            wins: 26,
            timeoutMatches: 0,
            monsterWinRate: 1,
            winningRemainingHpRatio: 0.999212,
            score: 1.009992
        })
    }),
    Object.freeze({
        id: "elite-5-1-healer-laser-shockwave-siphon-siphon",
        size: 5,
        monsterTypes: Object.freeze(["healer", "laser", "shockwave", "siphon", "siphon"]),
        metrics: Object.freeze({
            matches: 26,
            wins: 26,
            timeoutMatches: 0,
            monsterWinRate: 1,
            winningRemainingHpRatio: 0.998982,
            score: 1.00999
        })
    })
]);

export function getEliteMobCombination(combinationId) {
    return ELITE_MOB_COMBINATIONS.find((combination) => combination.id === combinationId) ?? null;
}

export function pickEliteMobCombination(rng = Math.random) {
    const index = Math.floor(Math.max(0, Math.min(0.999999, rng())) * ELITE_MOB_COMBINATIONS.length);
    return ELITE_MOB_COMBINATIONS[index] ?? ELITE_MOB_COMBINATIONS[0];
}
